name: main-action
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run test
      - uses: actions/first-interaction@v1.1.0
        with:
          # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: secrets.GITHUB_TOKEN
          # Comment to post on an individual's first issue
          issue-message: "Gratz"
          # Comment to post on an individual's first pull request
          pr-message: "Gratz på första pull request"
